swagger: "2.0"

info:
  version: "0.0.0"
  title: subscription service

# Currently using this only because it results in the generator having a name
# for the API client (results in SubscriptionApi as opposed to DefaultApi).
tags:
  - name: subscription

paths:
  /subscriptions:
    post:
      tags:
        - subscription
      description: Create a new subscription.
      parameters:
        - name: body
          required: true
          in: body
          description: The parameters from which the subscription should be created.
          schema:
            $ref: "#/definitions/SubscriptionParams"
      responses:
        201:
          description: The Subscriber owning the newly created subscription.
          schema:
            $ref: "#/definitions/Subscriber"
        400:
          description: A set of errors describing why the parameters did not result in a subscription.
          schema:
            type: array
            items:
              $ref: "#/definitions/Error"

  /subscriptions/{id}:
    get:
      description: Fetch an existing subscription.
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
          description: The subscription id.
      responses:
        200:
          description: The subscriber owning the subscription.
          schema:
            $ref: "#/definitions/Subscriber"
        404:
          description: An indication that no subscription by that id exists.

definitions:
  Error:
    description: A minimal error object based on JSON API error objects.
    required:
      - title
      - detail
    properties:
      title:
        type: string
        description: A short summary of the problem.
      detail:
        type: string
        description: An explanation of the problem.

  Psp:
    description: The payment service provider.
    type: string
    enum:
      - Apple
      - Stripe

  SubscriptionParams:
    description: The request object to create a new Subscription.
    required:
      - subscriberId
      - planId
      - pricePointId
      - psp
      - token
    properties:
      subscriberId:
        type: integer
        format: int64
      planId:
        type: integer
        format: int64
      pricePointId:
        type: integer
        format: int64
      psp:
        $ref: "#/definitions/Psp"
      token:
        type: string

  Coupon:
    description: TODO
    required:
      - percentageOff
      - status
    properties:
      percentageOff:
        type: integer
        format: int64
      expirationDate:
        type: string
        format: date-time
      status:
        type: string
        
  Entitlements:
    description: TODO
    properties:
      maxGroups:
        type: integer
        format: int32
      maxUsers:
        type: integer
        format: int32
        
  Plan:
    description: The Subscription plan.
    required:
      - name
      - entitlements
    properties:
      name:
        type: string
      entitlements:
        $ref: "#/definitions/Entitlements"
        
  PricePoint:
    description: The Subscription price point.
    required:
      - amount
      - currency
    properties:
      amount:
        type: number
      currency:
        type: string
      renewalDuration:
        type: integer
        format: int64
      renewalDurationUnit:
        type: string
      trialDuration:
        type: integer
        format: int64
      trialDurationUnit:
        type: string
        
  Charge:
    description: TODO
    required:
      - amount
      - currency
      - date
      - status
    properties:
      amount:
        type: number
      currency:
        type: string
      date:
        type: string
        format: date-time
      status:
        type: string
        
  Invoice:
    description: TODO
    required:
      - amount
      - currency
      - date
      - charges
      - status
    properties:
      amount:
        type: number
      currency:
        type: string
      date:
        type: string
        format: date-time
      charges:
        type: array
        items:
          $ref: "#/definitions/Charge"
      coupon:
        $ref: "#/definitions/Coupon"
      status:
        type: string
        
  Subscription:
    description: A Subscription.
    required:
      - startDate
      - plan
      - pricePoint
      - invoices
      - status
      - psp
    properties:
      startDate:
        type: string
        format: date-time
      endDate:
        type: string
        format: date-time
      trialStartDate:
        type: string
        format: date-time
      trialEndDate:
        type: string
        format: date-time
      plan:
        $ref: "#/definitions/Plan"
      pricePoint:
        $ref: "#/definitions/PricePoint"
      renewalPlan:
        $ref: "#/definitions/Plan"
      renewalPricePoint:
        $ref: "#/definitions/PricePoint"
      invoices:
        type: array
        items:
          $ref: "#/definitions/Invoice"
      status:
        type: string
      psp:
        $ref: "#/definitions/Psp"
        
  Subscriber:
    description: A Subscriber provides data about an organizer in the context of its subscriptions.
    required:
      - id
      - identifier
      - inactiveSubscriptions
      - coupons
      - status
      - created
      - modified
    properties:
      id:
        type: integer
        format: int64
      identifier:
        type: string
      availableSubscription:
        $ref: "#/definitions/Subscription"
      inactiveSubscriptions:
        type: array
        items:
          $ref: "#/definitions/Subscription"
      coupons:
        type: array
        uniqueItems: true
        items:
          $ref: "#/definitions/Coupon"
      status:
        type: string
      created:
        type: string
        format: date-time
      modified:
        type: string
        format: date-time