swagger: "2.0"

host: "pequod.pequod.mup-prod.mup.zone"

schemes: [ http ]

info:
  version: "1.0.0"
  title: Pequod service

paths:
  /event_add:
    post:
      description: add event details to pequod backend. make it searchable
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/EventEntityCreate"
      description: add event details to pequod backend. make it searchable
      responses:
        200:
          description: Ok
          type: string

  /event_delete/{id}:
    post:
      description: remove an event from pequod backend
      parameters:
        - name: id
          in: path
          description: event id
          type: integer

definitions:
  EventEntityCreate:
    required:
      - id
      - lat
      - lon
      - title
      - desc
    properties:
      id:
        type: integer
        format: int32
      lat:
        type: number
        format : float
      lon:
        type: number
        format : float
      title:
        type: string
      desc:
        type: string
